import type { ItemDetail, ProviderWaitDetail, TaskSeed, TurnObservation, UsageSnapshot } from "@telar/engine-client";
import type { ClaudeSessionRuntime } from "./runtime";
import type { SdkCanUseTool, ClaudeTurnBindings, ClaudeSdk, ClaudeEffort } from "./sdk";
import type { LimitWarningSeen } from "./limits";
import type { OpenBlock, StreamingInput } from "./observations";
import type { BackgroundClaim } from "./background-claims";

export const COALESCE_MS = 16;

export type TurnState = {
  sdk: ClaudeSdk;
  cwd: string;
  sdkEffort: ClaudeEffort | undefined;
  computerUseServer: Record<string, unknown> | undefined;
  contextEnv: Record<string, string> | undefined;
  compactionEnv: Record<string, string | undefined> | undefined;
  defaultEnv: Record<string, string>;
  finalText: string;
  receivedPartialText: boolean;
  reportedSessionId: string | undefined;
  usage: UsageSnapshot | undefined;
  completed: boolean;
  contextUsed: number | undefined;
  contextMax: number | undefined;
  lastEnvelopeUsage: unknown;
  waitItemId: string | undefined;
  lastLimitWarning: LimitWarningSeen | undefined;
  endTurnSeenAt: number | undefined;
  ownResultRead: boolean;
  silenceTimer: ReturnType<typeof setTimeout> | undefined;
  standingLimit: { resumeAt: number; limitType?: ProviderWaitDetail["limitType"] } | undefined;
  compactionItemId: string | undefined;
  compactionSucceeded: boolean;
  compactionMeasured: boolean;
  openBlocks: Map<string, OpenBlock>;
  openTools: Map<string, { id: string; detail: ItemDetail; }>;
  streamingInputs: Map<string, StreamingInput>;
  openTopLevelTools: Set<string>;
  planItemId: string | undefined;
  taskIdsBySdkId: Map<string, string>;
  knownTasks: Map<string, TaskSeed>;
  taskTypesBySdkId: Map<string, string>;
  suppressedTasks: Set<string>;
  pendingOutputFiles: Map<string, string>;
  foreignTurn: { taskId: string | undefined } | undefined;
  ownTurnOpen: boolean;
  sink: (observations: TurnObservation[]) => Promise<void>;
  runtimeRef: ClaudeSessionRuntime<ClaudeTurnBindings, TaskSeed> | undefined;
  pending: TurnObservation[];
  flushQueue: Promise<unknown>;
  pendingSink: ((observations: TurnObservation[]) => Promise<void>) | undefined;
  coalescing: ReturnType<typeof setTimeout> | undefined;
  canUseTool: SdkCanUseTool | undefined;
  backgroundClaim: BackgroundClaim | undefined;
  backgroundClaimChain: Promise<unknown>;
  executable: string | undefined;
  extraArgs: Record<string, string | null> | undefined;
  turnBindings: ClaudeTurnBindings;
  streaming: boolean;
  briefings: string[];
  readOnly: boolean;
  fingerprintFields: Record<string, unknown>;
  fingerprint: string;
  fingerprintDigests: Record<string, string>;
  childEnv: Record<string, string> | undefined;
  persistent: boolean;
  outgoing: Record<string, string> | undefined;
  claimed: ClaudeSessionRuntime<ClaudeTurnBindings, TaskSeed> | undefined;
  runtime: ClaudeSessionRuntime<ClaudeTurnBindings, TaskSeed>;
  turnUuid: string;
  ownSends: Set<string>;
  steerSent: boolean;
  turnDone: boolean;
  outstandingSteerCuts: Set<symbol>;
  streamEnded: boolean;
  cancelReap: (() => void) | undefined;
};

export type Rest<F> = F extends (ctx: never, ...rest: infer R) => unknown ? R : never;
