// Generated by scripts/settings-index.mjs from the rows the panes render; do not edit.
import { ArchiveIcon, AudioLinesIcon, BellIcon, BookMarkedIcon, BoxesIcon, ClockIcon, CopyIcon, DownloadIcon, ExternalLinkIcon, FileWarningIcon, FolderGitIcon, FolderKanbanIcon, FolderPlusIcon, GaugeIcon, GitBranchIcon, GitPullRequestIcon, GlobeIcon, HardDriveIcon, HistoryIcon, ImageIcon, KeyRoundIcon, LanguagesIcon, LayersIcon, LockIcon, MicIcon, MonitorIcon, MoonIcon, NetworkIcon, PackageIcon, RefreshCwIcon, RotateCcwIcon, ScrollTextIcon, ShieldCheckIcon, SmartphoneIcon, SparklesIcon, StethoscopeIcon, TerminalIcon, TrashIcon, TypeIcon, VariableIcon, Volume2Icon } from "lucide-react";
import type { SettingsGroupSpec } from "./search";

export const GENERATED_PAGES: readonly { id: string; groups: readonly SettingsGroupSpec[] }[] = [
  { id: "general", groups: [
    { "title":"New sessions", rows: [
      {"title":"Model","hint":"The provider, model and options a new session starts with.","keywords":["provider","default model","effort","reasoning","fast mode","claude","codex","opencode"],"icon":SparklesIcon},
      {"title":"Access level","keywords":["permissions","supervised","auto","full access","approval","runtime mode","prompts"],"icon":ShieldCheckIcon},
      {"title":"Workspace","keywords":["worktree","branch","git","isolation"],"icon":FolderGitIcon},
    ] },
    { "title":"Organization", rows: [
      {"title":"Settle quiet sessions","hint":"Pinned sessions and open questions stay put.","keywords":["inbox","archive","auto","shelf","settled","unsettle","restore","hidden","put away","quiet","hours","days","window"]},
      {"title":"Settle delegated sessions","hint":"Once their result is delivered. A failed errand, a pinned row and an open question all stay put.","keywords":["delegated","errand","coordinator","handoff","result","settle","hours","days","window"]},
      {"title":"Continue after a usage limit resets","hint":"A Claude turn stopped by a usage limit runs again once the limit lifts. A session can still change its own.","keywords":["rate limit","usage limit","resume","five-hour","weekly","claude"],"icon":RefreshCwIcon},
      {"title":"Continue after Telar restarts","hint":"When Telar restarts to update, the sessions it stopped pick up where they left off.","keywords":["resume","restart","update","continue","interrupted"],"icon":RotateCcwIcon},
      {"title":"Group sessions by project","hint":"Off, the rail is one list, newest first, with spawned sessions under the one that started them.","keywords":["group by","flat","none","list","sidebar","order","newest"]},
    ] },
    { "title":"Text generation", rows: [
      {"title":"Written by","hint":"The provider, model and effort that name sessions and branches.","keywords":["claude","codex","opencode","driver","title model","textgen","reasoning","thinking","effort"]},
      {"title":"Name sessions","keywords":["title","rename","automatic"]},
      {"title":"Name branches","hint":"Renames branches the engine cut to match the session. Yours keep their names.","keywords":["git","branch name","title","rename branches"]},
    ] },
    { "title":"About", rows: [
      {"title":"Version","keywords":["about","this build"]},
      {"title":"Engine","keywords":["daemon","offline","health"]},
      {"title":"Update status","keywords":["upgrade","download","version","updates"]},
      {"title":"Channel","keywords":["beta","nightly","stable","release","updates"]},
      {"title":"Install on quit","keywords":["restart","automatic","updates"]},
    ] },
    { "title":"Experimental", rows: [
    ] },
  ] },
  { id: "appearance", groups: [
    { rows: [
      {"title":"Colour scheme","hint":"Which state the app wears, and the one Background edits.","keywords":["light","dark","system","theme","mode"]},
    ] },
    { "title":"Background", rows: [
      {"title":"Base","hint":"The app colour. It decides the hue and how colourful the surfaces are; the lightness that keeps text readable is kept underneath.","keywords":["colour","color","theme","palette","hue","tint","background","canvas"]},
      {"title":"Match the other state","keywords":["light","dark","copy","sync","both"]},
    ] },
    { "title":"Type and surfaces", rows: [
      {"title":"Accent","hint":"The one hue that means a person acted — buttons, links, the caret.","keywords":["colour","color","highlight","primary","hue"]},
      {"title":"Depth","hint":"How far raised surfaces — cards, the composer, menus — sit off the page.","keywords":["shadow","elevation","flat","soft","deep","raised"],"icon":LayersIcon},
    ] },
    { "title":"Window", rows: [
      {"title":"Translucency","hint":"Rebuilds the window.","keywords":["glass","blur","clear","frost","vibrancy","transparent"]},
      {"title":"Layers through canvas and rail","keywords":["show-through","show through","opacity","wallpaper","backdrop","layers"]},
      {"title":"Chat width","hint":"How wide the conversation and the composer can grow.","keywords":["wide","full","comfortable","column","measure","transcript"]},
    ] },
  ] },
  { id: "keybindings", groups: [
  ] },
  { id: "providers", groups: [
    { "title":"Agent catalog", rows: [
    ] },
    { "title":"Usage providers","keywords":["cliproxy","cliproxyapi","hub","proxy","quota","limit","limits","usage","pooled","rate limit","5h","weekly","remaining"], rows: [
    ] },
    { "title":"Diagnosis", rows: [
      {"title":"Diagnose usage","hint":"An agent reads this computer's usage in the background, read-only, and explains what drives it.","keywords":["diagnose","diagnosis","high usage","why","tokens","cost","spend","expensive","report"],"icon":StethoscopeIcon},
    ] },
  ] },
  { id: "integrations", groups: [
    { "title":"Browser profiles","keywords":["cookies","account","sign in","chrome","profile","default","browser","integrations"], rows: [
    ] },
    { "title":"Site permissions", rows: [
      {"title":"Nothing decided yet","hint":"Telar asks the first time a site wants something, over the browser's address bar.","keywords":["camera","microphone","mic","webcam","notifications","location","geolocation","clipboard","screen share","screen sharing","permission","permissions","allow","block","revoke","site"]},
    ] },
    { "title":"Remembered logins","keywords":["1password","password","credential","autofill","revoke","vault","integrations"], rows: [
      {"title":"Offer to remember after you sign in","hint":"After you type a login in Telar's browser, ask whether agents may reuse it.","keywords":["1password","save login","remember","offer","prompt","password"]},
      {"title":"Use a password manager in the browser","hint":"Lets Telar's browser and agents fill logins from your password manager.","keywords":["1password","extension","autofill","disable","off","credential","integrations"]},
    ] },
    { "title":"Links", rows: [
      {"title":"Open in the session's browser","keywords":["external","system browser","tabs"],"icon":ExternalLinkIcon},
    ] },
    { "title":"Simulators", rows: [
      {"title":"Simulators","hint":"Who may list, start and use the simulators on this Mac.","keywords":["simulator","emulator","iphone","ios","android","device","xcode","agent","agent-device","tap","automation"]},
    ] },
    { "title":"Agent tools", rows: [
      {"title":"Tell agents they are inside Telar","hint":"A paragraph each turn and a skill file for each provider, so agents read Telar's words the way you mean them.","keywords":["orientation","preamble","system prompt","prompt","context","skill","SKILL.md","instructions","telar","show the text"]},
    ] },
    { "title":"Sign-in", rows: [
    ] },
    { "title":"Add a server", rows: [
    ] },
    { "title":"Also in play here", rows: [
    ] },
    { rows: [
      {"title":"Computer use","keywords":["cua","driver","automation","engine","access","permission","privacy","accessibility","screen recording","grant"],"icon":MonitorIcon},
    ] },
    { "title":"Dictation", rows: [
      {"title":"Provider","keywords":["dictation","dictate","microphone","mic","voice","speech","transcribe","transcription","provider","off","disable","turn off","turn on","enable","deepgram"]},
      {"title":"Language","keywords":["spanish","english","automatic","multilingual","locale"],"icon":LanguagesIcon},
      {"title":"Service key","keywords":["dictation","dictate","microphone","mic","voice","speech","transcribe","transcription","deepgram","key","api key","credential"],"icon":KeyRoundIcon},
      {"title":"Vocabulary","keywords":["dictation","vocabulary","glossary","keyterm","keyterms","terms","custom words","jargon","names","spelling","accuracy","wrong word"],"icon":BookMarkedIcon},
    ] },
    { "title":"Microphone", rows: [
      {"title":"Input","keywords":["input","device","which microphone","choose microphone","headset","airpods","usb","interface","built-in","default input","wrong microphone"],"icon":MicIcon},
      {"title":"Level","keywords":["level","meter","volume","test microphone","not hearing","no audio","silent","muted","dead","check"],"icon":AudioLinesIcon},
      {"title":"Live transcript","keywords":["demo","preview","try","live","test transcription","interim","rewritten","see it working"],"icon":TypeIcon},
    ] },
  ] },
  { id: "plugins", groups: [
    { "title":"Plugins", rows: [
    ] },
    { rows: [
      {"title":"Add plugin from folder","keywords":["install","plugin","folder","link","remove","uninstall","plugin.json"],"icon":FolderPlusIcon},
      {"title":"Default packages","hint":"Installed into environments Telar creates from here on. Nothing is installed into an environment that already exists.","keywords":["pandas","numpy","packages","pip","environment","data science"],"icon":PackageIcon,"id":"plugins-data-science-packages"},
    ] },
    { "title":"TeX distribution", rows: [
      {"title":"Telar (managed)","keywords":["tectonic","latex","install","tex","download"],"icon":DownloadIcon,"id":"plugins-latex-managed"},
    ] },
  ] },
  { id: "projects", groups: [
    { "title":"Identity", rows: [
      {"title":"Name","hint":"Shown in the rail, the pickers and session headers. The folder on disk is not renamed.","keywords":["rename","title","project name"],"icon":FolderKanbanIcon},
      {"title":"Icon","keywords":["avatar","favicon","logo","mark"],"icon":ImageIcon},
      {"title":"Checkout","keywords":["root","path","folder","directory"],"icon":FolderGitIcon},
    ] },
    { "title":"New conversations", rows: [
      {"title":"Default model","keywords":["model","per project","default"],"icon":SparklesIcon},
      {"title":"Model options","hint":"New conversations in this project start with this model and these options.","keywords":["effort","reasoning","fast mode","per project"],"icon":GaugeIcon},
      {"title":"Where new conversations start","keywords":["worktree","checkout","workspace","branch"],"icon":FolderGitIcon},
    ] },
    { "title":"Sign-in", rows: [
    ] },
    { "title":"Add a server", rows: [
    ] },
    { "title":"Also in play here", rows: [
    ] },
    { "title":"New worktrees", rows: [
      {"title":"Worktree preparation","keywords":["setup","prepare","inherit","worktree"],"icon":FileWarningIcon},
      {"title":"Repo file","keywords":["config file","committed","telar.json","repo"],"icon":FileWarningIcon},
      {"title":"Setup","hint":"Runs in the background in each new worktree, with the variables and ports below.","keywords":["install","bootstrap","prepare","script","timeout","env","variables","export","port","server","collide","build output","regenerate","cache","generated"],"icon":TerminalIcon},
      {"title":"Environment","hint":"Exported to the setup command.","keywords":["install","bootstrap","prepare","script","timeout","env","variables","export","port","server","collide","build output","regenerate","cache","generated"],"icon":VariableIcon},
      {"title":"Ports","hint":"One stable port per name, exported under that name.","keywords":["install","bootstrap","prepare","script","timeout","env","variables","export","port","server","collide","build output","regenerate","cache","generated"],"icon":NetworkIcon},
      {"title":"Artifacts","hint":"Output a worktree can regenerate. Telar never runs the command.","keywords":["install","bootstrap","prepare","script","timeout","env","variables","export","port","server","collide","build output","regenerate","cache","generated"],"icon":PackageIcon},
      {"title":"Dependencies","hint":"How a new worktree gets node_modules and .venv: install them with the setup command, share the checkout's, or neither.","keywords":["node_modules","venv","install","share","symlink","disk"],"icon":BoxesIcon},
    ] },
    { "title":"Removed from Telar", rows: [
      {"title":"Restore this project","hint":"Same id, same settings, same sessions. Registering the folder again does this too.","keywords":["undo","restore","removed","unarchive"]},
    ] },
    { "title":"Danger", rows: [
      {"title":"Remove project from Telar","hint":"No new sessions can start on it. Files on disk are not touched, and you can put it back.","keywords":["unregister","delete","forget","put away"]},
    ] },
    { "title":"Data science", rows: [
      {"title":"Data science for this project","keywords":["python","jupyter","notebook","kernel","enable","plugin"]},
    ] },
    { "title":"Python tools", rows: [
      {"title":"uv","keywords":["python","install","package manager"]},
      {"title":"conda","keywords":["anaconda","miniconda","environment"]},
      {"title":"Python","keywords":["interpreter","version","install python"]},
    ] },
    { "title":"Environments", rows: [
    ] },
    { "title":"Python packages", rows: [
    ] },
    { "title":"Environment", rows: [
      {"title":"Environment","icon":PackageIcon},
      {"title":"Install packages","keywords":["pip","package","install","dependencies"],"icon":DownloadIcon},
      {"title":"The project's own dependencies","hint":"Install everything the checkout already declares.","keywords":["requirements","pyproject","dependencies","sync"],"icon":PackageIcon},
    ] },
    { "title":"LaTeX", rows: [
      {"title":"LaTeX for this project","keywords":["latex","tex","enable","plugin"]},
      {"title":"Default document","keywords":["main file","main.tex","document","entry"]},
      {"title":"Engine","hint":"What latexmk drives. pdflatex unless the document needs system fonts (xelatex, lualatex)."},
    ] },
    { "title":"Distributions", rows: [
    ] },
    { "title":"TeX packages", rows: [
    ] },
  ] },
  { id: "notifications", groups: [
    { "title":"Alerts", rows: [
      {"title":"Notify on","hint":"Which device each alert goes to.","keywords":["duplicate","twice","desktop notifications","banner","iphone","mac","idle","away","push"],"icon":BellIcon},
      {"title":"Notification sounds","hint":"The sound this computer's alerts play.","keywords":["sound","chime","audio","mute","silent","hilo","armonico","felt"],"icon":Volume2Icon},
    ] },
    { "title":"Phones","keywords":["notifications","apns","alerts","push","relay","phone","not working","test notification","paused","registered"], rows: [
    ] },
  ] },
  { id: "source-control", groups: [
    { "title":"Source control", rows: [
      {"title":"GitHub","keywords":["gh","git","pull request","issues","token","auth","sign in","cli","forge","gitlab"],"icon":GitPullRequestIcon},
    ] },
  ] },
  { id: "storage", groups: [
    { "title":"Worktrees", rows: [
      {"title":"Delete inactive worktrees","hint":"Releases the worktree of a session inactive this many days. Its branch and conversation are kept, and it comes back when you reopen the session.","keywords":["cleanup","clean up","disk","space","free","full","reclaim","checkout","idle","old","days"],"icon":ClockIcon},
      {"title":"Release settled worktrees","hint":"Releases a settled session's worktree after this many days; its branch and conversation are kept.","keywords":["cleanup","clean up","disk","space","free","reclaim","checkout","settled","days"],"icon":MoonIcon},
      {"title":"Delete unchanged worktrees","hint":"Releases the worktree of an idle session whose branch has no commits beyond the default branch.","keywords":["cleanup","clean up","disk","space","reclaim","checkout","unchanged","empty","branch"],"icon":GitBranchIcon},
      {"title":"Delete worktrees of archived sessions","hint":"Otherwise archiving keeps the worktree.","keywords":["cleanup","clean up","disk","space","reclaim","checkout","archive"],"icon":ArchiveIcon},
      {"title":"Worktree folder","keywords":["worktree","checkout","external","drive","move","space","disk","relocate","worktree folder","how many","size"],"icon":FolderGitIcon},
      {"title":"Clean up","keywords":["clean up now","cleanup","sweep","free space","disk","run"],"icon":SparklesIcon},
    ] },
    { "title":"Where worktrees live", rows: [
    ] },
    { "title":"By state", rows: [
    ] },
    { "title":"Checkouts", rows: [
    ] },
    { "title":"Logs", rows: [
      {"title":"Delete old logs","hint":"Rotated logs only.","keywords":["cleanup","clean up","disk","space","logs","rotate","days"],"icon":ScrollTextIcon},
      {"title":"Turn journal retention","keywords":["retention","journal","export","retire","idle"],"icon":HistoryIcon},
    ] },
    { "title":"Terminals", rows: [
      {"title":"Terminals settled sessions may keep open","keywords":["terminal","process","dev server","shell","limit","cap","running","settled"]},
    ] },
    { "title":"Store", rows: [
      {"title":"Data folder","keywords":["external","volume","drive","where","path","ssd"],"icon":HardDriveIcon},
      {"title":"Safe copy","keywords":["backup","copy","export","move store"],"icon":CopyIcon},
      {"title":"Previous store","keywords":["old store","cleanup","free space","retired"],"icon":TrashIcon},
    ] },
  ] },
  { id: "connections", groups: [
    { "title":"This Mac", rows: [
      {"title":"Require pairing","keywords":["auth","security","phone","ipad"],"icon":SmartphoneIcon},
      {"title":"Network access","keywords":["expose","lan","loopback","address"],"icon":GlobeIcon},
      {"title":"HTTPS on your private network","keywords":["tailscale","tailnet","magicdns","certificate","serve"],"icon":LockIcon},
    ] },
    { "title":"Devices that reach this Mac", rows: [
      {"title":"Pair a device","keywords":["qr","link","token","pairing code","phone","ipad"],"icon":SmartphoneIcon},
      {"title":"Revoke all other devices","hint":"Keeps this one — the lost-phone button. Any of them can pair again with a new code.","keywords":["sign out","logout","lost","stolen"]},
    ] },
    { "title":"Computers this Mac reaches", rows: [
      {"title":"Add a computer","keywords":["host","pair","second machine","remote","mac","computer"]},
    ] },
  ] },
];
