
import {
  BlocksIcon,
  AArrowDownIcon,
  AArrowUpIcon,
  AppWindowIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BlendIcon,
  BugIcon,
  ExternalLinkIcon,
  CircleDotIcon,
  FileCodeIcon,
  FileSearchIcon,
  FolderCogIcon,
  FolderGit2Icon,
  FolderOpenIcon,
  FolderPlusIcon,
  GaugeIcon,
  GitCompareIcon,
  GitPullRequestIcon,
  GlobeIcon,
  HashIcon,
  MaximizeIcon,
  MessageSquareIcon,
  MessageSquarePlusIcon,
  MessagesSquareIcon,
  MicIcon,
  PaletteIcon,
  PictureInPicture2Icon,
  PanelLeftIcon,
  PanelRightIcon,
  PinIcon,
  PuzzleIcon,
  RefreshCwIcon,
  SearchIcon,
  SendIcon,
  Settings2Icon,
  SettingsIcon,
  SmartphoneIcon,
  SquareIcon,
  SquarePenIcon,
  SquarePlusIcon,
  SquareTerminalIcon,
  SunMoonIcon,
  SwatchBookIcon,
  TextCursorIcon,
  TextSearchIcon,
  type LucideIcon,
} from "lucide-react";
import { COMMANDS, type CommandGroup, type CommandId } from "./commands";

export const COMMAND_ICONS: Record<string, LucideIcon> = {
  "a-arrow-down": AArrowDownIcon,
  "a-arrow-up": AArrowUpIcon,
  "app-window": AppWindowIcon,
  blocks: BlocksIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-up": ArrowUpIcon,
  blend: BlendIcon,
  bug: BugIcon,
  "circle-dot": CircleDotIcon,
  "file-code": FileCodeIcon,
  "file-search": FileSearchIcon,
  "folder-cog": FolderCogIcon,
  "folder-git-2": FolderGit2Icon,
  "external-link": ExternalLinkIcon,
  "folder-open": FolderOpenIcon,
  "folder-plus": FolderPlusIcon,
  gauge: GaugeIcon,
  "git-compare": GitCompareIcon,
  "git-pull-request": GitPullRequestIcon,
  globe: GlobeIcon,
  hash: HashIcon,
  maximize: MaximizeIcon,
  "message-square-plus": MessageSquarePlusIcon,
  "messages-square": MessagesSquareIcon,
  mic: MicIcon,
  palette: PaletteIcon,
  "picture-in-picture-2": PictureInPicture2Icon,
  "panel-left": PanelLeftIcon,
  "panel-right": PanelRightIcon,
  pin: PinIcon,
  puzzle: PuzzleIcon,
  "refresh-cw": RefreshCwIcon,
  search: SearchIcon,
  send: SendIcon,
  settings: SettingsIcon,
  "settings-2": Settings2Icon,
  smartphone: SmartphoneIcon,
  square: SquareIcon,
  "square-pen": SquarePenIcon,
  "square-plus": SquarePlusIcon,
  "square-terminal": SquareTerminalIcon,
  "sun-moon": SunMoonIcon,
  "swatch-book": SwatchBookIcon,
  "text-cursor": TextCursorIcon,
  "text-search": TextSearchIcon,
};

export const GROUP_ICONS: Record<CommandGroup, LucideIcon> = {
  Session: MessageSquareIcon,
  Rail: PanelLeftIcon,
  Panel: PanelRightIcon,
  Application: SettingsIcon,
};

export function iconByName(name: string | undefined): LucideIcon | undefined {
  return name ? COMMAND_ICONS[name] : undefined;
}

export function commandIcon(id: CommandId): LucideIcon {
  const command = COMMANDS.find((entry) => entry.id === id);
  return iconByName(command?.icon) ?? GROUP_ICONS[command?.group ?? "Application"];
}
