// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "TelarMobileLogic",
    platforms: [.macOS(.v15)],
    targets: [
        .target(name: "TelarMobile", path: ".", sources: [
            "Shared/SessionActivityRow.swift",
            "TelarMobile/Features/Composer/ComposerCompletions.swift",
            "TelarMobile/Features/Composer/ComposerHost.swift",
            "TelarMobile/Features/Composer/ComposerLog.swift",
            "TelarMobile/Features/Composer/ComposerReference.swift",
            "TelarMobile/Features/Composer/ComposerSend.swift",
            "TelarMobile/Features/Composer/ComposerSkillsCache.swift",
            "TelarMobile/Features/Composer/ComposerTextEdit.swift",
            "TelarMobile/Features/Composer/ComposerTrigger.swift",
            "TelarMobile/Features/Composer/MobileDrafts.swift",
            "TelarMobile/Features/Composer/SessionDraft.swift",
            "TelarMobile/Features/Dictation/DictationAPI.swift",
            "TelarMobile/Features/Dictation/DictationModels.swift",
            "TelarMobile/Features/Dictation/DictationStrip.swift",
            "TelarMobile/Features/Dictation/DictationTranscript.swift",
            "TelarMobile/Features/Dictation/SpeakableText.swift",
            "TelarMobile/Features/Dictation/SpokenReply.swift",
            "TelarMobile/Features/Files/FileTree.swift",
            "TelarMobile/Features/Files/FilesAPI.swift",
            "TelarMobile/Features/Git/GitAPI.swift",
            "TelarMobile/Features/Hosts/Host.swift",
            "TelarMobile/Features/Hosts/HostLabel.swift",
            "TelarMobile/Features/Hosts/HostMigration.swift",
            "TelarMobile/Features/Hosts/HostsAPI.swift",
            "TelarMobile/Features/Hosts/LegacyHostMigration.swift",
            "TelarMobile/Features/Hosts/Pairing.swift",
            "TelarMobile/Features/Panel/DescribeError.swift",
            "TelarMobile/Features/Panel/PanelModels.swift",
            "TelarMobile/Features/Panel/PanelRaise.swift",
            "TelarMobile/Features/Panel/PanelTab.swift",
            "TelarMobile/Features/Plugins/InlineHtmlImages.swift",
            "TelarMobile/Features/Plugins/NotebookFile.swift",
            "TelarMobile/Features/Plugins/PandasHtmlTable.swift",
            "TelarMobile/Features/Plugins/PluginUI.swift",
            "TelarMobile/Features/Plugins/PluginsAPI.swift",
            "TelarMobile/Features/Plugins/TableWindows.swift",
            "TelarMobile/Features/Projects/FolderPath.swift",
            "TelarMobile/Features/Projects/ProjectHeaderMenu.swift",
            "TelarMobile/Features/Projects/ProjectsAPI.swift",
            "TelarMobile/Features/Prompts/PromptStash.swift",
            "TelarMobile/Features/Providers/CatalogModels.swift",
            "TelarMobile/Features/Providers/ModelChoice.swift",
            "TelarMobile/Features/Providers/ModelFamilies.swift",
            "TelarMobile/Features/Providers/ProvidersAPI.swift",
            "TelarMobile/Features/Push/ActivityReport.swift",
            "TelarMobile/Features/Push/AutomaticCard.swift",
            "TelarMobile/Features/Push/PushAPI.swift",
            "TelarMobile/Features/Push/PushRegistration.swift",
            "TelarMobile/Features/Push/PushRelay.swift",
            "TelarMobile/Features/Remote/RemoteAPI.swift",
            "TelarMobile/Features/Remote/RemoteModels.swift",
            "TelarMobile/Features/Sessions/InboxStore.swift",
            "TelarMobile/Features/Sessions/MergedInbox.swift",
            "TelarMobile/Features/Sessions/NewConversationDraft.swift",
            "TelarMobile/Features/Sessions/NewConversationModel.swift",
            "TelarMobile/Features/Sessions/NewConversationTargets.swift",
            "TelarMobile/Features/Sessions/ReadReceipt.swift",
            "TelarMobile/Features/Sessions/SessionHeads.swift",
            "TelarMobile/Features/Sessions/SessionModels.swift",
            "TelarMobile/Features/Sessions/SessionNesting.swift",
            "TelarMobile/Features/Sessions/SessionRowMenu.swift",
            "TelarMobile/Features/Sessions/SessionStore.swift",
            "TelarMobile/Features/Sessions/SessionSync.swift",
            "TelarMobile/Features/Sessions/SessionSyncEngine.swift",
            "TelarMobile/Features/Sessions/SessionsAPI.swift",
            "TelarMobile/Features/Sessions/SettledShelf.swift",
            "TelarMobile/Features/Sessions/Settling.swift",
            "TelarMobile/Features/Sessions/SidebarMode.swift",
            "TelarMobile/Features/Sessions/SidebarModel.swift",
            "TelarMobile/Features/Sessions/TaskModels.swift",
            "TelarMobile/Features/Settings/AppSettings.swift",
            "TelarMobile/Features/Simulators/MJPEGParts.swift",
            "TelarMobile/Features/Simulators/SimulatorModels.swift",
            "TelarMobile/Features/Simulators/SimulatorsAPI.swift",
            "TelarMobile/Features/Transcript/ItemModels.swift",
            "TelarMobile/Features/Transcript/TranscriptFollow.swift",
            "TelarMobile/Features/Transcript/TurnLayout.swift",
            "TelarMobile/Features/Turns/QuestionDraft.swift",
            "TelarMobile/Features/Turns/RequestModels.swift",
            "TelarMobile/Features/Turns/TurnModels.swift",
            "TelarMobile/Features/Turns/TurnsAPI.swift",
            "TelarMobile/Features/Usage/UsageAPI.swift",
            "TelarMobile/Features/Usage/UsageReport.swift",
            "TelarMobile/Platform/EngineAPI.swift",
            "TelarMobile/Platform/EventModels.swift",
            "TelarMobile/Platform/Journal.swift",
            "TelarMobile/Platform/Primitives.swift",
            "TelarMobile/Platform/SnapshotCache.swift",
            "TelarMobile/Platform/TokenVault.swift",
            "TelarMobile/UI/MathSegments.swift",
            "TelarMobile/UI/StreamingReveal.swift",
        ]),
        .testTarget(name: "TelarMobileTests", dependencies: ["TelarMobile"], path: "TelarMobileTests"),
    ],
    swiftLanguageModes: [.v5]
)
